version: "3"
services:
  db:
    image: postgres:16
    shm_size: 1gb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

volumes:
  postgres:
  redis:

