name: Tests

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 21.x
              uses: actions/setup-node@v3
              with:
                  node-version: 21.x
            - run: npm ci
            - run: npm run ci:test
