name: 'Bump Version optionally deploy dev environment'

on:
    push:
        branches:
            - 'dev'

jobs:
    bump-version:
        if: ${{ !contains(github.event.head_commit.message, '#skip-deploy') }}
        name: 'Bump Version on dev'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: 'Checkout source code'
              uses: 'actions/checkout@v2'
              with:
                  ref: ${{ github.ref }}
                  token: ${{ secrets.BUMP_PAT }}
            - name: 'cat package.json'
              run: cat ./package.json
            - name: 'Automated Version Bump'
              id: version-bump
              uses: 'phips28/gh-action-bump-version@master'
              with:
                  tag-prefix: 'v'
                  version-type: 'patch'
                  commit-message: 'CI: bumps version to {{version}} [skip ci]'
              env:
                  GITHUB_TOKEN: ${{ secrets.BUMP_PAT }}
            - name: 'cat package.json'
              run: cat ./package.json
            - name: 'Output Step'
              env:
                  NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
              run: echo "new tag $NEW_TAG"
    # deploy-dev:
    #     env:
    #         DEPLOY_DEV: ${{secrets.DEPLOY_DEV}}
    #     if: ${{ env.DEPLOY_DEV == 'true' && !contains(github.event.head_commit.message, '#skip-deploy') }}
    #     uses: Krakaw/bootstrap-express/.github/workflows/manual_deploy.yml@dev
    #     with:
    #         ENVIRONMENT: 'dev'
    #     secrets: inherit
